Add Event indexer
l2beat/lz-monitoring pull request #45
Opened 2023-10-26 10:02 UTC by michalsidzej

Resolves L2B-2863, L2B-2874

2023-10-26 15:09 UTC, sdlyy requested changes
LG, few small things - let's discuss event indexer implementation since I want to be on the same page regarding final data flow

2023-10-26 15:09 UTC, sdlyy commented on packages/backend/src/indexers/EventIndexer.test.ts
> +        startBlock + 10,
Let's limit magic numbers
```suggestion
        startBlock + maxEventRange,
```

2023-10-26 15:09 UTC, sdlyy commented on packages/backend/src/indexers/EventIndexer.ts
Let's sync regarding event indexer tmrw

2023-10-26 15:58 UTC, michalsidzej commented on packages/backend/src/peripherals/database/EventRepository.test.ts
> +  })
Good point

2023-10-26 16:06 UTC, michalsidzej commented on packages/backend/src/indexers/EventIndexer.test.ts
> +        startBlock + 10,
[f749fae](https://github.com/l2beat/lz-monitoring/pull/45/commits/f749fae1338885babc9e10cf309ea107fb655626)

2023-10-27 10:18 UTC, sdlyy commented on packages/backend/src/peripherals/database/EventRepository.test.ts
Let's seal `deleteAfter`

2023-10-27 10:36 UTC, michalsidzej commented on packages/backend/src/peripherals/database/EventRepository.test.ts
[4cbc7fa](https://github.com/l2beat/lz-monitoring/pull/45/commits/4cbc7fac58cecd1bdafba26aa1ab5a50bfb02f65)

2023-10-27 11:44 UTC, sdlyy approved these changes
n i c e 🚀

2023-10-27 11:55 UTC, merged